// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// example_lapacke_dgels
void example_lapacke_dgels();
RcppExport SEXP _lapacker_example_lapacke_dgels() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    example_lapacke_dgels();
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_lapacker_example_lapacke_dgels", (DL_FUNC) &_lapacker_example_lapacke_dgels, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_lapacker(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
