# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@title Example: using lapacke_dgels
#'@description Solve linear systems using lapacke_dgels
#'@examples
#'## Expected output:
#'example_lapacke_dgels()
#'@export
example_lapacke_dgels <- function() {
    invisible(.Call('_lapacker_example_lapacke_dgels', PACKAGE = 'lapacker'))
}

